---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-restarts-check
  namespace: kuberhealthy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-restarts-check
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["events", "pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-restarts-check
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-restarts-check
subjects:
  - kind: ServiceAccount
    name: pod-restarts-check
    namespace: kuberhealthy
---
apiVersion: kuberhealthy.github.io/v2
kind: HealthCheck
metadata:
  name: pod-restarts
  namespace: kuberhealthy
spec:
  runInterval: 5m
  timeout: 10m
  podSpec:
    spec:
      serviceAccountName: pod-restarts-check
      containers:
        - name: pod-restarts
          image: kuberhealthy/pod-restarts-check:sha-<short-sha>
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAMESPACE
              value: "kube-system"
            - name: MAX_FAILURES_ALLOWED
              value: "10"
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
      restartPolicy: Never
